### ISSUE TITLE
Provide example of using data powered templates and pages

### ISSUE THREAD

**Issue by paulrobertlloyd** [webpro/component-styleguide-example#1]
Some context: I’ve looked briefly at Pattern Lab, and have used other templating languages before (Twig, Liquid) but don’t have much familiarity with Handlebars or Mustache. Given enough examples however, I can quickly pick up how something works. And if documentation refers to the terminology used in different templating languages, I then know what to search for to get further information.

---

This boilerplate example for Component Styleguide has been really helpful in getting me set up quickly, building out HTML components and styling them using Sass (I’m a big fan of using the `script` feature in package.json too). Now, I’m at the stage where I want to arrange molecules and organisms into templates and pages, but I’m a bit lost as to what’s the recommended approach using this tool.

I tried using the documentation for Pattern Lab, not because I know it works the same, but because the tool is inspired by it. I created a template, and then created a page, with a corresponding `.json` file, with that data required for that page instance, but that didn’t work. I’m guessing the only place data lives in this tool is in the data folder, which is fine. But then, how do I create pages with showing different content, based of certain templates? It’s unclear.

As a guide to using Component Styleguide, it would be helpful if this boilerplate demonstrated the full workflow, that is, pages with different data sources, possibly using the same template, which itself is a collection of organisms (which are a collection of molecules which uses an atom etc.).

Also, how do you create atoms and molecules with default values, which can be overridden with data later? For example, a button can say ‘Button text’ by default, but changed to say ‘Submit’ if certain JSON data dictates. This is where my lack of handlebars knowledge comes in, so it’s on me to learn! But an example of how to achieve this would be helpful, too.

Really enjoying the minimalist nature of the tool; just a bit more guidance/examples would be a real benefit.

Thanks,

Paul

**Comment by webpro** [comment]
OK let's see if I can clear things up a little:
- Other components can be included using e.g. `{{>atoms/button}}`. This works because all components are registered as partials to Handlebars.
- Data is indeed read from the `/data` folder only.
- To use different data (or "context") for a specific component, Handlebars supports a syntax such as `{{>atoms/button text="Submit"}}` (with a template like `<button>{text}</button`).

You can pass also pass an object as context to components/partials as in `{{>atoms/list items=items}}`. Where `items` are coming from `/data/items.json`. Then you can make a variation using `{{>atoms/list items=alternative_items}}` (from `/data/alternative_items.json`). Or use one data file, but use e.g. `{{>atoms/list items=section.items}}` and `{{>atoms/list items=section.others}}`.

Hopefully this gets you going, but feel free to ask and I'm happy to discuss.

**Comment by paulrobertlloyd** [comment]
> You can pass also pass an object as context to components/partials as in `{{>atoms/list items=items}}`.

I think this was the vital piece of information I was missing (the handlebars documentation can be a bit vague at times). I will update my component library with this information, and hopefully, once I’ve got the hang of it, update the examples in this repo. Thanks!

**Comment by paulrobertlloyd** [comment]
Do you have any tips on how to give components defaults values (i.e. for when they appear in the atoms/molecules libraries)? I’ve been doing the following:

``` html
<button>{{#if value}}{{value}}{{else}}Button text{{/if}}</button>
```

Yet, with a lot of dynamic content within a partial, this can get unwieldy. I thought I could do this:

``` html
<button>{{value value="Button text"}}</button>
```

but seems that was wishful thinking! The only other option is to do the following:

``` html
<button>{{value}}</button>
```

but that means the component will appear in the library views without content.

**Comment by webpro** [comment]
> I think this was the vital piece of information I was missing

Great; I was hoping I could summarize it the way I did :-) But indeed the docs and this example repo can be improved.

> Do you have any tips on how to give components defaults values

Can't think of much else than setting up some kind of data structure that allows to pass different context objects to components as their data (e.g. like the `{{>atoms/list items=alternative_items}}` example).

**Comment by webpro** [comment]
Closing this old issue, feel free to re-open.
